### ISSUE TITLE
UseCase Programming

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#46]
[zum Stoff: IT, Programmieren]
Spielen mit Objektumgebung, Informationen herausziehen (z.B.)
Einzelne Zugfolgen per Javascript Situationsangepasst
Zweite, Erste, Letzte Ebene automatisch
Vollständiger Lösungsalgorithmus und ensprechende Inspektoren liegen vor (FEHLT)

**Comment by SimonLentner** [comment]
https://ide.cube.codes/app/?init=loadFromUrl&url=https://share-repository.cube.codes/v1/appStates/ceaa8cb3-82bf-4cbe-bc55-cb2ed9bdcba9


//Teste Variante 4
await CUBE.setSolved();
await CUBE.rotate(Dimension.Z,1);
await CUBE.move(" U' "); 

// Variablen definieren
let HANS = CUBELETS.findSolvedInPart(CubePart.UF);
UI.log("HANS liegt (qua Def.) ursprünglich bei: " + HANS.initialPart.toString() + "\n"
+"HANS liegt aktuell an der Stelle: " + HANS.currentPart.toString() + "\n"
+"HANS gehört nach Mittenfarben nach: " + HANS.solvedPart.toString());
let Obenfarbe = CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
UI.log("OBENFARBE (der Mitte) ist: " + Obenfarbe + "\n"
+"HANS hat von oben die Farbe und von oben ist seine Farbe: " + HANS.getColorAt(CubeFace.UP));

//HANS liegt in der 1. Ebene (obersten Ebene)
//PS: Vielleicht die einfachsten Züge zuerst?
if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.FRONT) == Obenfarbe) {
	UI.log("Spiele Variante 1");
	await CUBE.move(" F E F E' ");
}
else if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.UP) == Obenfarbe) {
	UI.log("Spiele Variante 2 (nichts tun)");
	await CUBE.move(" ");
}
else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.RIGHT) == Obenfarbe) {
	UI.log("Spiele Variante 3");
	await CUBE.move(" R' F' "); 
}
else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.UP) == Obenfarbe) {
	UI.log("Spiele Variante 4");
	await CUBE.move(" R R D' F F ");
}
else UI.log("Spiele...?");

**Comment by SimonLentner** [comment]
Wolfgangs Pseudocode for fixing the edge UF

CUBE.mrs.kante1()
{
//HANS liegt in der 1. Ebene (obersten Ebene)
if(HANS v & HANS1 außen) move(FEFE');
if(HANS v & HANS1 oben) nix zu tun;
if(HANS r & HANS1 außen) move(R'F');
if(HANS r & HANS1 oben) move(RRD'FF);
if(HANS h & HANS1 außen) move(BE'F);
if(HANS h & HANS1 oben) move(BBDDFF);
if(HANS l & HANS1 außen) move(LF);
if(HANS l & HANS1 oben) move(LE'F');
//HANS liegt in der 2. Ebene (mittlere Ebene)
if(HANS vr & HANS1 rechts) move(F');
if(HANS vr & HANS1 vorne) move(EFE');
if(HANS hr & HANS1 rechts) move(EEFEE);
if(HANS hr & HANS1 hinten) move(EF'E');
if(HANS hl & HANS1 links) move(EEF'EE);
if(HANS hl & HANS1 hinten) move(E'FE);
if(HANS vl & HANS1 links) move(F);
if(HANS vl & HANS1 vorne) move(E'F'E);
//HANS liegt in der 3. Ebene (unterste Ebene)
if(HANS v & HANS1 außen) move(F'EF);
if(HANS v & HANS1 unten) move(FF);
if(HANS r & HANS1 außen) {move(D'); move(F'EF);}
if(HANS r & HANS1 unten) move(D'FF);
if(HANS h & HANS1 außen) {move(DD); move(F'EF);}
if(HANS h & HANS1 unten) move(DDFF);
if(HANS l & HANS1 außen) {move(D); move(F'EF);}
if(HANS l & HANS1 unten) move(DFF);
}
CUBE.mrs.kantenkreuz1()
{
for(i=1; i<5; ++i)
{CUBE.mrs.kante1(); move(y);}
}

**Comment by wolfganglentner** [comment]
https://ide.cube.codes/app/?init=loadFromUrl&url=https://share-repository.cube.codes/v1/appStates/d636f6f1-4545-4303-b10e-42a49f10b6b4

async function mrs_WeissOben(){
	UI.log("function mrs_WeissOben();");
	let weisseMitte=CUBELETS.findInitiallyInPart(CubePart.U);
	switch(weisseMitte.currentPart)
	{
		case CubePart.U: break;
		case CubePart.F: await CUBE.move(" x "); break;
		case CubePart.D: await CUBE.move(" x x "); break;
		case CubePart.B: await CUBE.move(" x' "); break;
		case CubePart.R: await CUBE.move(" z' "); break;
		case CubePart.L: await CUBE.move(" z "); break;
	}
	return;
}

async function mrs_WeissObenGruenVorne(){
	UI.log("function mrs_WeissObenGruenVorne();");
	await mrs_WeissOben();
	let grueneMitte=CUBELETS.findInitiallyInPart(CubePart.F);
	switch(grueneMitte.currentPart)
	{
		case CubePart.F: break;
		case CubePart.R: await CUBE.move(" y "); break;
		case CubePart.B: await CUBE.move(" y y "); break;
		case CubePart.L: await CUBE.move(" y' "); break;
	}
	return;
}

async function mrs_GelbOben(){
	UI.log("function mrs_GelbOben();");
	let gelbeMitte=CUBELETS.findInitiallyInPart(CubePart.D);
	switch(gelbeMitte.currentPart)
	{
		case CubePart.U: break;
		case CubePart.F: await CUBE.move(" x "); break;
		case CubePart.D: await CUBE.move(" x x "); break;
		case CubePart.B: await CUBE.move(" x' "); break;
		case CubePart.R: await CUBE.move(" z' "); break;
		case CubePart.L: await CUBE.move(" z "); break;
	}
	return;
}

async function mrs_Kante1(){
	UI.log("function mrs_Kante1();");
	let kanteUF=CUBELETS.findSolvedInPart(CubePart.UF);
	let obenFarbe=CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
	switch(kanteUF.currentPart)
	{
		case CubePart.UF: 
			if(kanteUF.getColorAt(CubeFace.FRONT)==obenFarbe) await CUBE.move(" F E' F E "); 
			else await CUBE.move(" "); 
			break;
		case CubePart.UR: 
			if(kanteUF.getColorAt(CubeFace.UP)==obenFarbe) await CUBE.move(" R' E' F E "); 
			else await CUBE.move(" R' F' "); 
			break;
		case CubePart.BU: 
			if(kanteUF.getColorAt(CubeFace.UP)==obenFarbe) await CUBE.move(" B B D D F F "); 
			else await CUBE.move(" B' E' F' E "); 
			break;
		case CubePart.LU: 
			if(kanteUF.getColorAt(CubeFace.UP)==obenFarbe) await CUBE.move(" L E F' E' "); 
			else await CUBE.move(" L F "); 
			break;
		case CubePart.LF: 
			if(kanteUF.getColorAt(CubeFace.FRONT)==obenFarbe) await CUBE.move(" E F' E' "); 
			else await CUBE.move(" F "); 
			break;
		case CubePart.FR: 
			if(kanteUF.getColorAt(CubeFace.FRONT)==obenFarbe) await CUBE.move(" E' F E "); 
			else await CUBE.move(" F' "); 
			break;
		case CubePart.RB: 
			if(kanteUF.getColorAt(CubeFace.BACK)==obenFarbe) await CUBE.move(" E' F' E "); 
			else await CUBE.move(" E E F E E"); 
			break;
		case CubePart.BL: 
			if(kanteUF.getColorAt(CubeFace.BACK)==obenFarbe) await CUBE.move(" E F E' "); 
			else await CUBE.move(" E E F' E E "); 
			break;
		case CubePart.FD: 
			if(kanteUF.getColorAt(CubeFace.DOWN)==obenFarbe) await CUBE.move(" F F "); 
			else await CUBE.move(" D' M D M' "); 
			break;
		case CubePart.RD: 
			if(kanteUF.getColorAt(CubeFace.DOWN)==obenFarbe) await CUBE.move(" D' F F "); 
			else await CUBE.move(" M D' M' "); 
			break;
		case CubePart.DB: 
			if(kanteUF.getColorAt(CubeFace.DOWN)==obenFarbe) await CUBE.move(" D D F F "); 
			else await CUBE.move(" D M D M' "); 
			break;
		case CubePart.DL: 
			if(kanteUF.getColorAt(CubeFace.DOWN)==obenFarbe) await CUBE.move(" D F F "); 
			else await CUBE.move(" M D M' "); 
			break;
	}
	return;
}

async function mrs_Kantenkreuz1() { 
	UI.log("function mrs_Kantenkreuz1();");
	for(i=1; i<5; ++i) {await mrs_Kante1(); await CUBE.move(" y "); }
}

async function mrs_Ecke1(){
	UI.log("function mrs_Ecke1();");
	let eckeUFR=CUBELETS.findSolvedInPart(CubePart.UFR);
	let obenFarbe=CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
	switch(eckeUFR.currentPart)
	{
		case CubePart.UFR: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.UP): break;
				case eckeUFR.getColorAt(CubeFace.FRONT): await CUBE.move(" F D F' D D R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.RIGHT): await CUBE.move(" R' D' R D D F D' F' "); break;
			}
			break;
		case CubePart.URB: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.UP): await CUBE.move(" B' D' B D' R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.BACK): await CUBE.move(" B' D' B D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.RIGHT): await CUBE.move(" R D R' D R' D R "); break;
			}
			break;
		case CubePart.ULF: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.UP): await CUBE.move(" R D R' D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.FRONT): await CUBE.move(" F D' F' D' F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.LEFT): await CUBE.move(" L D L' D' R' D R "); break;
			}
			break;
		case CubePart.UBL: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.UP): await CUBE.move(" B D B' D D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.BACK): await CUBE.move(" B D B' R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.LEFT): await CUBE.move(" L' D' L F D' F' "); break;
			}
			break;
		case CubePart.DRF: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.FRONT): await CUBE.move(" D' R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.RIGHT): await CUBE.move(" D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.DOWN): await CUBE.move(" R' D D R D D F D' F' "); break;
			}
			break;
		case CubePart.DBR: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.DOWN): await CUBE.move(" D' R' D D R D D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.BACK): await CUBE.move(" F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.RIGHT): await CUBE.move(" D D R' D R "); break;
			}
			break;
		case CubePart.DLB: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.DOWN): await CUBE.move(" B D' B' D' R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.BACK): await CUBE.move(" D R' D R "); break;
				case eckeUFR.getColorAt(CubeFace.LEFT): await CUBE.move(" D' F D' F' "); break;
			}
			break;
		case CubePart.DFL: 
			switch(obenFarbe)
			{
				case eckeUFR.getColorAt(CubeFace.DOWN): await CUBE.move(" D R' D' D' R D D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.FRONT): await CUBE.move(" D D F D' F' "); break;
				case eckeUFR.getColorAt(CubeFace.LEFT): await CUBE.move(" R' D R "); break;
			}
			break;
	}
	return;
}

async function mrs_Eckenkranz1() { 
	UI.log("function mrs_Eckenkranz1();");
	for(i=1; i<5; ++i) {await mrs_Ecke1(); await CUBE.move(" y "); }
}

async function mrs_Ebene1() { 
	UI.log("function mrs_Ebene1();");
	await mrs_Kantenkreuz1();
	await mrs_Eckenkranz1();
}

async function mrs_WeisseEbene1() { 
	UI.log("function mrs_WeisseEbene1();");
	await mrs_WeissObenGruenVorne(); await mrs_Ebene1(); 
}

async function mrs_Mango() { 
	UI.log("function mrs_Mango();");
	await CUBE.move(" D' R' D R F' R F R' "); 
}

async function mrs_MangoMirror() { 
	UI.log("function mrs_MangoMirror();");
	await CUBE.move(" D F D' F' R F' R' F "); 
}

async function mrs_Kante2(){
	UI.log("function mrs_Kante2();");
	let kanteFR=CUBELETS.findSolvedInPart(CubePart.FR);
	let vorneFarbe=CUBELETS.findCurrentlyInPart(CubePart.F).getColorAt(CubeFace.FRONT);
	switch(kanteFR.currentPart)
	{
		case CubePart.LF: await CUBE.move(" y' "); await mrs_Mango(); await CUBE.move(" y "); await mrs_Kante2(); break;
		case CubePart.FR: await mrs_Mango(); await mrs_Kante2(); break;
		case CubePart.RB: await CUBE.move(" y "); await mrs_Mango(); await CUBE.move(" y' "); await mrs_Kante2(); break;
		case CubePart.BL: await CUBE.move(" y y "); await mrs_Mango(); await CUBE.move(" y y "); await mrs_Kante2(); break;
		case CubePart.FD: 
			if(kanteFR.getColorAt(CubeFace.FRONT)==vorneFarbe) await mrs_Mango(); 
			else { await CUBE.move(" D "); await mrs_MangoMirror(); } 
			break;
		case CubePart.RD: 
			if(kanteFR.getColorAt(CubeFace.DOWN)==vorneFarbe) await mrs_MangoMirror(); 
			else { await CUBE.move(" D' "); await mrs_Mango(); } 
			break;
		case CubePart.DB: 
			if(kanteFR.getColorAt(CubeFace.DOWN)==vorneFarbe) { await CUBE.move(" D' "); await mrs_MangoMirror(); } 
			else { await CUBE.move(" D D "); await mrs_Mango(); }  
			break;	
		case CubePart.DL: 
			if(kanteFR.getColorAt(CubeFace.LEFT)==vorneFarbe) { await CUBE.move(" D "); await mrs_Mango(); } 
			else { await CUBE.move(" D D "); await mrs_MangoMirror(); }  
			break;
			
	}
	return;
}

async function mrs_Ebene2() { 
	UI.log("function mrs_Ebene2WeissOben();");
	for(i=1; i<5; ++i) { await mrs_Kante2(); await CUBE.move(" y "); } 
}

async function mrs_WeisseEbene2() { 
	UI.log("function mrs_WeisseEbene2n();");
	await mrs_WeisseEbene1(); await mrs_Ebene2(); await mrs_GelbOben();
}

async function mrs_Bingo(){
	UI.log("function mrs_Bingo();");
	await CUBE.move(" R U R' U' R' F R F' ");
}

async function mrs_Kanten3Positionieren(){
	UI.log("function mrs_Kanten3Positionieren();");
	//Kante LU Positionieren
	let kanteLU=CUBELETS.findSolvedInPart(CubePart.LU);
	switch(kanteLU.currentPart){
		case CubePart.LU: break;	
		case CubePart.BU: await CUBE.move(" U' "); break;
		case CubePart.UR: await CUBE.move(" U U "); break;
		case CubePart.UF: await CUBE.move(" U "); break;
	}
	//Kante BU Positionieren
	let kanteBU=CUBELETS.findSolvedInPart(CubePart.BU);
	switch(kanteBU.currentPart){
		case CubePart.BU: break;	
		case CubePart.UR: await mrs_Bingo(); break;
		case CubePart.UF: await mrs_Bingo(); await mrs_Bingo(); break;
	}
	//Kante UR Positionieren
	let kanteUR=CUBELETS.findSolvedInPart(CubePart.UR);
	switch(kanteUR.currentPart){
		case CubePart.UR: break;
		case CubePart.UF: 
			await CUBE.move(" U "); 
			await mrs_Bingo(); await mrs_Bingo(); 
			await CUBE.move(" U U "); 
		break;
	}
}

async function mrs_Menno(){
	UI.log("function mrs_Menno();");
	await CUBE.move(" E R E R E R E R ");
	return;
}

async function mrs_Kanten3Drehen(){
	UI.log("function mrs_Kanten3Drehen();");
	let obenWandfarbe=CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
	//Kante UR evtl. Drehen
	for(i=1; i<5; ++i) {
		let obenKantenfarbe=CUBELETS.findCurrentlyInPart(CubePart.UR).getColorAt(CubeFace.UP);
		if(obenWandfarbe!=obenKantenfarbe) await mrs_Menno();
		await CUBE.move(" U ");
	}
}

async function mrs_Claudia(){
	UI.log("function mrs_Claudia();");
	await CUBE.move(" L' U R U' L U R' U' ");
	return;
}

async function mrs_Ecken3Positionieren(){
	UI.log("function mrs_Ecken3Positionieren();");
	let found=false;
	for(i=1; i<5; ++i){
		let eckeUFR=CUBELETS.findSolvedInPart(CubePart.UFR);
		if(eckeUFR.currentPart==CubePart.UFR) {
			found=true;
			while(CUBELETS.findSolvedInPart(CubePart.ULF).currentPart!=CubePart.ULF) {
				await mrs_Claudia();
			}
		}
		if(found) break;
		await CUBE.move(" y ");	
	}
	if(!found) {
		await mrs_Claudia();
		while(CUBELETS.findSolvedInPart(CubePart.UFR).currentPart!=CubePart.UFR) { //Terminiert beweisbar jetzt
			await CUBE.move(" y ");	
		}
		while(CUBELETS.findSolvedInPart(CubePart.ULF).currentPart!=CubePart.ULF) {
				await mrs_Claudia();
			}
	}
	
}

async function mrs_Benno(){
	UI.log("function mrs_Benno();");
	await CUBE.move(" R F' R' F R F' R' F ");
	return;
}

async function mrs_Ecken3Drehen(){
	UI.log("function mrs_Ecken3Drehen();");
	let obenWandfarbe=CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
	for(i=1; i<5; ++i){
		let eckeUFR=CUBELETS.findCurrentlyInPart(CubePart.UFR);
		while(eckeUFR.getColorAt(CubeFace.UP)!=obenWandfarbe) {
			await mrs_Benno();
		}
		await CUBE.move(" U ");
	}
}

//Main
await mrs_WeisseEbene2();
await mrs_Kanten3Positionieren();
await mrs_Kanten3Drehen();
await mrs_Ecken3Positionieren();
await mrs_Ecken3Drehen();
