### ISSUE TITLE
Cannot use in script windows static variables from Model

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#67]
I want to implement the following

const CUBELETS = CUBE.cubelets; //@LL: in Api

// Verdrehen zu einer Testsituation für den 3. Fall unten
CUBE.rotate(Dimension.Z,1);
CUBE.move(" U' ");

// Variablen definieren
let HANS = CUBELETS.findSolvedInPart(CubePart.UF);
API.log("Liegt ursprünglich dh. hat Farben: " + HANS.initialPart.toString() + "\n"
	+ "Liegt aktuell an der Stelle: " + HANS.initialPart.toString() + "\n"
	+ "Gehört nach Mittenfarben nach: " + HANS.initialPart.toString());
let Obenfarbe: CubeFace = CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
API.log("Die Obenfarbe (der Mitte) ist: " + Obenfarbe + "\n"
	+ "und von oben ist seine Farbe: " + HANS.getColorAt(CubeFace.UP));
	//HANS liegt in der 1. Ebene (obersten Ebene)
if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.FRONT) == Obenfarbe) CUBE.move(" F E F E' ");
else if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.UP) == Obenfarbe) CUBE.move(" ");
else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.RIGHT) == Obenfarbe) CUBE.move(" R' F' ");	else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.UP) == Obenfarbe) CUBE.move(" R R D' F F ");

**Comment by lukaslentner** [comment]
Imported all Classes to global namespace...
Added CUBELETS

**Comment by lukaslentner** [comment]
This can run now: Please look at the dif!!!

// Verdrehen zu einer Testsituation für den 3. Fall unten
CUBE.rotate(Dimension.Z,1);
CUBE.move(" U' ");

// Variablen definieren
let HANS = CUBELETS.findSolvedInPart(CubePart.UF);
UI.log("Liegt ursprünglich dh. hat Farben: " + HANS.initialPart.toString() + "\n"
+ "Liegt aktuell an der Stelle: " + HANS.initialPart.toString() + "\n"
+ "Gehört nach Mittenfarben nach: " + HANS.initialPart.toString());
let Obenfarbe = CUBELETS.findCurrentlyInPart(CubePart.U).getColorAt(CubeFace.UP);
UI.log("Die Obenfarbe (der Mitte) ist: " + Obenfarbe + "\n"
+ "und von oben ist seine Farbe: " + HANS.getColorAt(CubeFace.UP));
//HANS liegt in der 1. Ebene (obersten Ebene)
if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.FRONT) == Obenfarbe) await CUBE.move(" F E F E' ");
else if (HANS.currentPart == CubePart.UF && HANS.getColorAt(CubeFace.UP) == Obenfarbe) await CUBE.move(" ");
else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.RIGHT) == Obenfarbe) await CUBE.move(" R' F' "); else if (HANS.currentPart == CubePart.UR && HANS.getColorAt(CubeFace.UP) == Obenfarbe) await CUBE.move(" R R D' F F ");
