### ISSUE TITLE
Color names

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#68]
Having Color aliases for CubeFaces would be nice, with fromInitialFace() toInitialFace(), and then rewrite the convenience methods to accept this

**Comment by lukaslentner** [comment]
@SimonLentner How about this:

There are 3 ColorSchemes I know of:
* Western (the one right now)
* Western Inverse (black for white)
* Japanese (White and Blue swapped)

We create 3 Color Schemes like
```
WesternColorScheme = {
  WHITE: CubeFace.UP,
  ...
}
```

and then in a script you can 

```
const Color = WesternColorScheme;
// and use it everywhere instead of CubeFace ...
```

**Comment by lukaslentner** [comment]
For me it would be also ok to preset Color=WesternColorScheme as it is really the default ... and only offer the other schemes, but somebody who wants to program with Japanese Colors must use `JapaneseColorScheme.WHITE` ...

**Comment by lukaslentner** [comment]
Maybe "CubeColor" instead of "Color" ???

**Comment by SimonLentner** [comment]
Good idea. Only disadvantage: In functions like ColorFromSide(....) the feedback should be actually a color, no?

**Comment by lukaslentner** [comment]
Well a Color is then a CubeFace. So you can always do (maybe that's what you afraid about to not be able to do):
```
const color1 = ...getColorFromSide()
if(color1 === Color.WHITE) ...
...setColor(color);
```
the fact that your color is actually a CubeFace never is important. You can compare it with a color as both are CubeFaces and in fact you are comparing cube faces... and you can use it everywhere as cube faces.

So the only things I see:
* They have of course CubeFace properties, as they are CubeFaces. But I think that makes sense.
* Maybe you find it strange that Color.WHITE is not the same as JapaneseColorScheme.WHITE ... but I find that quite consequent...
* You can use a color at a place where a CubeFace is requested and the analogy with color does not make sense. This might be the biggest disadvantage (you have no own type for the color), but I see currently no problem ...

**Comment by lukaslentner** [comment]
In a way Color = InitialCubeFace right?
