### ISSUE TITLE
Includes files for JavaScript in Scriptwindows

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#74]
* Define Functions and additional (?) methods for objects
* Include Files with Javascript codes that can lay in Wiki or Webseite etc.

**Comment by lukaslentner** [comment]
Already now possible:

Upload a script to your favorite webspace:

```
self.myvariable = 3;
self.myfunction = () => { return 3; };
```

(Creating members of the object `self` means creating variables/functions in the global namespace. All normal defined variables/functions will stay in the local scope of this javascript file and will not be available in the code window)

and then load the javascript via the following code in the code window:

```
const loadLibrary = async url => eval(await fetch(url).then(r => r.text()));

await loadLibrary('https://www.myserver.de/test.js');
UI.log(myvariable);
UI.log(myfunction());
```

Of course it makes sense to to add the `loadLibrary`function to our API later ...

**Comment by SimonLentner** [comment]
Great. Of course later in the API it would be good if "async function bla()" can stay, instead of "bla=()=>" because then there are two formats to define functions and one has to reformat (simply append to the text in the console windows? but if not also fine...)

But I could not get it to work, says "Type Error. Failed to Fetch"...

const loadLibrary = async url => eval(await fetch(url).then(r => r.text()));
await loadLibrary('https://github.com/cube-codes/cube-codes-website/files/6258048/MRSAlgorithmus_Library.txt');
await mrs.WeissOben();

**Comment by lukaslentner** [comment]
You can now:
await SYSTEM.loadLibrary('...');

**Comment by lukaslentner** [comment]
@SimonLentner 

You can write:
```
self.functionname = async function() {
//Body
}
```

which is better than the arrow notation if you are unused to it.

But either way you need to add the function to the global namespace "self".

A simple function declaration only creates a function in the local scope ... it is not that hard to rewrite and in general it might be better to namespace the functions from the library like this anyhow (we are not in C where we have to make namespaces via "mrs_" prefixing ...):
```
self.mrs = {
func1: async function() {...}
}

// and then in the editor window
await mrs.func1();
```
