### ISSUE TITLE
ShuffleByExplosion should not shuffle faces

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#84]
Papa, a quick fix for you would be:
let shuffleAlsPermutation=PermutationCubeState.fromShuffleByExplosion(CUBE.cube.spec)
shuffleAlsPermutation.permutations[2]=[0,1,2,3,4,5,6,7]; //Faces wieder in gelöste Reihenfolge
let PERMUTATIONCONVERTER=new PermutationCubeStateConverter(CUBE.cube.spec);
await CUBE.cube.setState(PERMUTATIONCONVERTER.toCubeState(shuffleAlsPermutation));

Lukas, you are right, for the NNN cube shuffle by explosion means fixing the innermost cubes. On the other hand, this simply determines "how" shuffled it gets, why would this choice be the right one? Eg if the 333 cube is constructed differently, exploding it would also permute the mids...anyway, of course this can be fixed...

**Comment by lukaslentner** [comment]
I understand. As all odd cubes I know of are constructed that way we should then simply offer a flag that ensures the "firm cross"

**Comment by lukaslentner** [comment]
@SimonLentner did it
